parameters:
# [Required] Job name
  name: ''
# [Required] Build agent name
  image: ''
# [Optional] Install additional tools command line
  installToolsCmd: ''
# [Required] URL to download the compiler
  compilerUrl: ''
# [Required] VCPKG triplet
  vcpkgTriplet: ''
# [Optional] Cmake additional arguments for CMake generate mode
  cmakeGenArgs: ''
# [Optional] Build configuration (Debug, Release)
  buildConfiguration: 'Release'
# [Optional] Enable run tests
  enableRunTests: true
# [Optional] Publish artifacts to a GitHub Release
  enablePublishToGitHub: false
# [Optional] Package suffix
  packageSuffix: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
    buildDirectory: 'build'
    installDir: '$(Build.ArtifactStagingDirectory)/install/bitserializer-$(Build.SourceBranchName)'
    archiveFilePath: '$(Build.ArtifactStagingDirectory)/install/bitserializer_$(Build.SourceBranchName)${{ parameters.packageSuffix }}.tar.gz'

  steps:
  - script: |
      echo --- Install build tools ---
      ${{ parameters.installToolsCmd }}
    displayName: 'Install build tools'
    condition: ne('${{ parameters.installToolsCmd }}', '')

  - script: |
      echo --- Download compiler ---
      wget -nv ${{ parameters.compilerUrl }} -O compiler.tar.xz
      echo --- Extract compiler ---
      sudo tar -xf compiler.tar.xz -C /usr/
    displayName: 'Install compiler'
    condition: ne('${{ parameters.compilerUrl }}', '')

  - script: |
      echo --- Clone latest VCPKG ---
      cd ..
      git clone --progress -v "https://github.com/Microsoft/vcpkg.git"
      echo --- VCPKG: Bootstrap ---
      cd vcpkg
      ./bootstrap-vcpkg.sh
    displayName: 'Install VCPKG'

  - task: Cache@2
    inputs:
      key: |
        vcpkg | v8 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      restoreKeys: |
        vcpkg | v8 | ${{ parameters.name }}
      path: ${{ variables.buildDirectory }}/vcpkg_installed/
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Configure cache of VCPKG packages

  - task: CMake@1
    inputs:
      workingDirectory: ${{ variables.buildDirectory }}
      cmakeArgs: '${{ parameters.cmakeGenArgs }} -DCMAKE_BUILD_TYPE=${{ parameters.buildConfiguration }} -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ parameters.vcpkgTriplet }} -DCMAKE_INSTALL_PREFIX:PATH=${{ variables.installDir }} .. -G Ninja'
    displayName: 'Cmake - generate [${{ parameters.buildConfiguration }}]'

  - script: |
      ninja -C ${{ variables.buildDirectory }}
    displayName: 'Build [${{ parameters.buildConfiguration }}]'

  - script: |
      cd ${{ variables.buildDirectory }}
      ctest -C ${{ parameters.buildConfiguration }} -T test --output-on-failure -j$(nproc)
    displayName: 'Run tests'
    continueOnError: true
    condition: and(succeeded(), eq('${{ parameters.enableRunTests }}', true))

  - task: PublishTestResults@2
    displayName: 'Publish Test results'
    condition: and(succeeded(), eq('${{ parameters.enableRunTests }}', true))
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/${{ variables.buildDirectory }}'
      testRunTitle: '${{ parameters.name }} [${{ parameters.buildConfiguration }}]'
      buildPlatform: 'x64'
      buildConfiguration: '${{ parameters.buildConfiguration }}'

  - script: |
      cd ${{ variables.buildDirectory }}
      cmake --build . --config ${{ parameters.buildConfiguration }} --target install
    condition: and(succeeded(), eq('${{ parameters.enablePublishToGitHub }}', true))
    displayName: 'Cmake - install [${{ parameters.buildConfiguration }}]'

  - task: ArchiveFiles@2
    displayName: Zip package
    condition: and(succeeded(), eq('${{ parameters.enablePublishToGitHub }}', true))
    inputs:
      rootFolderOrFile: '${{ variables.installDir }}'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '${{ variables.archiveFilePath }}'
      replaceExistingArchive: true

  - task: GitHubRelease@1
    displayName: 'Publish package to GitHub'
    condition: and(succeeded(), eq('${{ parameters.enablePublishToGitHub }}', true))
    inputs:
      gitHubConnection: 'PavelKisliak'
      repositoryName: '$(Build.Repository.Name)'
      action: 'edit'
      isDraft: true
      target: '$(Build.SourceVersion)'
      tag: $(Build.SourceBranchName)
      tagSource: 'userSpecifiedTag'
      title: '$(Build.SourceBranchName)'
      addChangeLog: false
      assets: '${{ variables.archiveFilePath }}'
      assetUploadMode: 'replace'
