parameters:
# [Required] Job name
  name: ''
# [Required] Build agent name
  image: ''
# [Optional] Install additional tools command line
  installToolsCmd: ''
# [Required] URL to download the compiler
  compilerUrl: ''
# [Required] VCPKG triplet
  vcpkgTriplet: ''
# [Optional] Cmake additional arguments for CMake generate mode
  cmakeGenArgs: ''
# [Optional] Build configuration (Debug, Release)
  buildConfiguration: 'Release'
# [Optional] Build directory
  buildDirectory: 'build'
# [Optional] Enable run tests
  enableRunTests: true

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}

  steps:
  - script: |
      echo --- Install build tools ---
      ${{ parameters.installToolsCmd }}
    displayName: 'Install build tools'
    condition: ne('${{ parameters.installToolsCmd }}', '')

  - script: |
      echo --- Download compiler ---
      wget -nv ${{ parameters.compilerUrl }} -O compiler.tar.xz
      echo --- Extract compiler ---
      sudo tar -xf compiler.tar.xz -C /usr/
    displayName: 'Install compiler'
    condition: ne('${{ parameters.compilerUrl }}', '')

  - script: |
      echo --- Clone latest VCPKG ---
      cd ..
      git clone --progress -v "https://github.com/Microsoft/vcpkg.git"
      echo --- VCPKG: Bootstrap ---
      cd vcpkg
      ./bootstrap-vcpkg.sh
    displayName: 'Install VCPKG'

  - task: Cache@2
    inputs:
      key: |
        vcpkg | v8 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      restoreKeys: |
        vcpkg | v8 | ${{ parameters.name }}
      path: ${{ parameters.buildDirectory }}/vcpkg_installed/
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Configure cache of VCPKG packages

  - task: CMake@1
    inputs:
      workingDirectory: ${{ parameters.buildDirectory }}
      cmakeArgs: '${{ parameters.cmakeGenArgs }} -DCMAKE_BUILD_TYPE=${{ parameters.buildConfiguration }} -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ parameters.vcpkgTriplet }} .. -G Ninja'
    displayName: 'Cmake - generate [${{ parameters.buildConfiguration }}]'

  - script: |
      ninja -C ${{ parameters.buildDirectory }}
    displayName: 'Build [${{ parameters.buildConfiguration }}]'

  - script: |
      cd ${{ parameters.buildDirectory }}
      ctest -C ${{ parameters.buildConfiguration }} -T test --output-on-failure
    displayName: 'Run tests'
    continueOnError: true
    condition: eq('${{ parameters.enableRunTests }}', true)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/${{ parameters.buildDirectory }}'
      testRunTitle: '${{ parameters.name }} [${{ parameters.buildConfiguration }}]'
      buildPlatform: 'x64'
      buildConfiguration: '${{ parameters.buildConfiguration }}'
    displayName: 'Publish Test results'
    condition: eq('${{ parameters.enableRunTests }}', true)
