parameters:
# [Required] Job name
  name: ''
# [Required] Build agent name
  image: ''
# [Optional] Platform [x64, win32]
  platform: 'x64'
# [Required] VCPKG triplet
  vcpkgTriplet: 'x64-windows'
# [Optional] Cmake additional arguments for CMake generate mode
  cmakeGenArgs: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
    VCPKG_CACHE_DIR: C:\Users\VssAdministrator\AppData\Local\vcpkg\archives

  steps:
  - script: |
      echo --- Clone latest VCPKG ---
      cd ..
      git clone --progress -v "https://github.com/Microsoft/vcpkg.git"
      echo --- VCPKG: Bootstrap ---
      cd vcpkg
      bootstrap-vcpkg
    displayName: 'Install VCPKG'

  - task: Cache@2
    inputs:
      key: |
        vcpkg | v8 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      restoreKeys: |
        vcpkg | v8 | ${{ parameters.name }}
      path: $(VCPKG_CACHE_DIR)
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Configure cache of VCPKG packages

  - script: |
      mkdir build
      cmake --version
    displayName: Make Build Directory

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '-A ${{ parameters.platform }} ${{ parameters.cmakeGenArgs }} -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/../vcpkg/scripts/buildsystems/vcpkg.cmake ..'
    displayName: 'Cmake - generate'

  - script: |
      cd build
      cmake --build . --config Debug
    displayName: 'Build [Debug]'

  - script: |
      cd build
      ctest -C Debug -T test --output-on-failure
    displayName: 'Run tests [Debug]'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/build'
      testRunTitle: '${{ parameters.name }} [Debug]'
      buildPlatform: '${{ parameters.platform }}'
      buildConfiguration: 'Debug'
    displayName: 'Publish Test results [Debug]'

  - script: |
      cd build
      cmake --build . --config Release
    displayName: 'Build [Release]'

  - script: |
      cd build
      ctest -C Release -T test --output-on-failure
    displayName: 'Run tests [Release]'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/build'
      testRunTitle: '${{ parameters.name }} [Release]'
      buildPlatform: '${{ parameters.platform }}'
      buildConfiguration: 'Release'
    displayName: 'Publish Test results [Release]'

