parameters:
# [Required] Job name
  name: ''
# [Required] Build agent name
  image: ''
# [Optional] Platform [x64, win32]
  platform: 'x64'
# [Required] VCPKG triplet
  vcpkgTriplet: 'x64-windows'
# [Optional] Cmake additional arguments for CMake generate mode
  cmakeGenArgs: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
    VCPKG_CACHE_DIR: ${VCPKG_DEFAULT_BINARY_CACHE}

  steps:
  - script: |
      echo --- VCPKG installation path: $(VCPKG_INSTALLATION_ROOT) ---
      cd $(VCPKG_INSTALLATION_ROOT)
      echo --- VCPKG binary cache path: $(VCPKG_CACHE_DIR) ---
    displayName: 'Update VCPKG'

  - task: Cache@2
    inputs:
      key: |
        vcpkg | v7 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      restoreKeys: |
        vcpkg | v7 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      path: $(VCPKG_CACHE_DIR)
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Configure cache of VCPKG packages

  - script: |
      mkdir build
    displayName: Make Build Directory

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '-A ${{ parameters.platform }} ${{ parameters.cmakeGenArgs }} -DCMAKE_TOOLCHAIN_FILE=$(VCPKG_INSTALLATION_ROOT)/scripts/buildsystems/vcpkg.cmake ..'
    displayName: 'Cmake - generate'

  - publish: $(VCPKG_INSTALLATION_ROOT)\buildtrees\
    artifact: CMake logs ($(Agent.JobName))
    displayName: Publishing CMake logs
    condition: failed()

  - script: |
      cd build
      cmake --build . --config Debug
    displayName: 'Build [Debug]'

  - script: |
      cd build
      ctest -C Debug -T test --output-on-failure
    displayName: 'Run tests [Debug]'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/build'
      testRunTitle: '${{ parameters.name }} [Debug]'
      buildPlatform: '${{ parameters.platform }}'
      buildConfiguration: 'Debug'
    displayName: 'Publish Test results [Debug]'

  - script: |
      cd build
      cmake --build . --config Release
    displayName: 'Build [Release]'

  - script: |
      cd build
      ctest -C Release -T test --output-on-failure
    displayName: 'Run tests [Release]'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/build'
      testRunTitle: '${{ parameters.name }} [Release]'
      buildPlatform: '${{ parameters.platform }}'
      buildConfiguration: 'Release'
    displayName: 'Publish Test results [Release]'

