parameters:
# [Required] Job name
  name: ''
# [Required] Build agent name
  image: ''
# [Optional] Platform [x64, win32]
  platform: 'x64'
# [Required] VCPKG triplet
  vcpkgTriplet: 'x64-windows'
# [Optional] Cmake additional arguments for CMake generate mode
  cmakeGenArgs: ''
# [Optional] Build configuration (Debug, Release)
  buildConfiguration: 'Release'
# [Optional] Enable run tests
  enableRunTests: true

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.image }}
  variables:
    VCPKG_CACHE_DIR: C:\Users\VssAdministrator\AppData\Local\vcpkg\archives

  steps:
  - script: |
      echo --- Clone latest VCPKG ---
      cd ..
      git clone --progress -v "https://github.com/Microsoft/vcpkg.git"
      echo --- VCPKG: Bootstrap ---
      cd vcpkg
      bootstrap-vcpkg
    displayName: 'Install VCPKG'

  - script: |
      mkdir build
      cmake --version
    displayName: Make Build Directory

  - task: Cache@2
    inputs:
      key: |
        vcpkg | v9 | ${{ parameters.name }} | $(Build.SourcesDirectory)/vcpkg.json
      restoreKeys: |
        vcpkg | v9 | ${{ parameters.name }}
      path: ./build/vcpkg_installed/
      cacheHitVar: VCPKG_CACHE_RESTORED
    displayName: Configure cache of VCPKG packages

  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '-A ${{ parameters.platform }} ${{ parameters.cmakeGenArgs }} -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/../vcpkg/scripts/buildsystems/vcpkg.cmake ..'
    displayName: 'Cmake - generate [${{ parameters.buildConfiguration }}]'

  - script: |
      cd build
      cmake --build . --config ${{ parameters.buildConfiguration }}
    displayName: 'Build [${{ parameters.buildConfiguration }}]'

  - script: |
      cd build
      ctest -C ${{ parameters.buildConfiguration }} -T test --output-on-failure
    displayName: 'Run tests'
    continueOnError: true
    condition: eq('${{ parameters.enableRunTests }}', true)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'cTest'
      testResultsFiles: '**/Testing/**/Test.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/build'
      testRunTitle: '${{ parameters.name }} [${{ parameters.buildConfiguration }}]'
      buildPlatform: '${{ parameters.platform }}'
      buildConfiguration: '${{ parameters.buildConfiguration }}'
    displayName: 'Publish Test results'
    condition: eq('${{ parameters.enableRunTests }}', true)
