/*******************************************************************************
* Copyright (C) 2018-2026 by Pavel Kisliak                                     *
* This file is part of BitSerializer library, licensed under the MIT license.  *
*******************************************************************************/
#pragma once
#include <string>
#include <string_view>
#include <functional>
#include <type_traits>

/**
 * @brief Declares a type as a string-like type for BitSerializer and provides its
 *        zero-copy string-view conversion.
 *
 * The macro generates `StringViewOf(...)` and `AssignString(...)` functions in the current
 * namespace, which are found via ADL by the serialization and conversion machinery.
 * This means the macro must be placed in the same namespace as the declared type.
 *
 * This form relies on member methods `data()`, `size()` and `assign(std::basic_string_view<char_type>)`
 * (the same convention as `std::basic_string`).
 *
 * Use `BITSERIALIZER_DECLARE_STRING_TYPE_EXPLICIT` to register a type with arbitrary member
 * function names.
 *
 * @param TYPE The string-like type to declare.
 *
 * @par Example:
 * @code
 * class MyString { ... }; // exposes data(), size() and assign(std::string_view)
 * BITSERIALIZER_DECLARE_STRING_TYPE(MyString)
 * @endcode
 */
#define BITSERIALIZER_DECLARE_STRING_TYPE(TYPE) \
	inline std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(&TYPE::data, std::declval<const TYPE&>()))>>>> \
	StringViewOf(const TYPE& value) noexcept \
	{ \
		return std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(&TYPE::data, std::declval<const TYPE&>()))>>>>(value.data(), value.size()); \
	} \
	inline void AssignString(TYPE& value, std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(&TYPE::data, std::declval<const TYPE&>()))>>>> str) \
	{ \
		value.assign(str); \
	}

/**
 * @brief Declares a type as a string-like type with explicit member functions.
 *
 * Same as `BITSERIALIZER_DECLARE_STRING_TYPE`, but allows specifying arbitrary member functions
 * via pointers:
 * - data method: returns a pointer to the string data (deduces the character type);
 * - size method: returns the number of characters;
 * - assign method: sets the value from `std::basic_string_view<char_type>`.
 *
 * Must be placed in the same namespace as the type.
 *
 * @param TYPE         The string-like type to declare.
 * @param DATA_METHOD  Pointer to a member function returning the string data.
 * @param SIZE_METHOD  Pointer to a member function returning the number of characters.
 * @param ASSIGN_METHOD Pointer to a member function accepting `std::basic_string_view<char_type>`.
 *
 * @par Example:
 * @code
 * class MyString { ... };
 * BITSERIALIZER_DECLARE_STRING_TYPE_EXPLICIT(MyString, &MyString::Data, &MyString::Size, &MyString::FromString)
 * @endcode
 */
#define BITSERIALIZER_DECLARE_STRING_TYPE_EXPLICIT(TYPE, DATA_METHOD, SIZE_METHOD, ASSIGN_METHOD) \
	inline std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(DATA_METHOD, std::declval<const TYPE&>()))>>>> \
	StringViewOf(const TYPE& value) noexcept \
	{ \
		return std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(DATA_METHOD, std::declval<const TYPE&>()))>>>>(std::invoke(DATA_METHOD, value), std::invoke(SIZE_METHOD, value)); \
	} \
	inline void AssignString(TYPE& value, std::basic_string_view<std::remove_const_t<std::remove_pointer_t<std::remove_reference_t<decltype(std::invoke(DATA_METHOD, std::declval<const TYPE&>()))>>>> str) \
	{ \
		std::invoke(ASSIGN_METHOD, value, str); \
	}

namespace BitSerializer::Convert::Detail
{
	/**
	 * @brief Checks whether a type is one of the supported character types.
	 */
	template <typename TSym>
	struct is_char_type : std::bool_constant<
		std::is_same_v<TSym, char> ||
		std::is_same_v<TSym, char16_t> ||
		std::is_same_v<TSym, char32_t> ||
		std::is_same_v<TSym, wchar_t>> {};

	/**
	 * @brief Returns a zero-copy string view for `std::basic_string` (default implementation).
	 *
	 * Custom string-like types provide their own overloads (generated by `BITSERIALIZER_DECLARE_STRING_TYPE`)
	 * which are found via ADL.
	 */
	template <typename TSym, typename TTraits, typename TAllocator>
	constexpr std::basic_string_view<TSym> StringViewOf(const std::basic_string<TSym, TTraits, TAllocator>& value) noexcept
	{
		return value;
	}

	/**
	 * @brief Assigns a string view to `std::basic_string` (default implementation).
	 */
	template <typename TSym, typename TTraits, typename TAllocator>
	void AssignString(std::basic_string<TSym, TTraits, TAllocator>& value, std::basic_string_view<TSym> str)
	{
		value.assign(str);
	}

	/**
	 * @brief Returns a string view for a C-string (used by the conversion machinery).
	 */
	template <typename TSym, std::enable_if_t<is_char_type<TSym>::value, int> = 0>
	constexpr std::basic_string_view<TSym> StringViewOf(const TSym* in) noexcept
	{
		return in;
	}

	/**
	 * @brief Determines whether a type is a string-like type.
	 *
	 * True when both a `StringViewOf(const T&)` and an `AssignString(T&, ...)` function are found
	 * (in the `BitSerializer::Convert::Detail` namespace or via ADL in the type's namespace).
	 * This excludes C-string pointers, which can be viewed but not assigned.
	 */
	template <typename T, typename = void>
	struct is_string_type : std::false_type {};

	template <typename T>
	struct is_string_type<T, std::void_t<
		decltype(StringViewOf(std::declval<const T&>())),
		decltype(AssignString(std::declval<T&>(), StringViewOf(std::declval<const T&>())))>> : std::true_type {};

	template <typename T>
	constexpr bool is_string_type_v = is_string_type<T>::value;
}
